# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2c3b8fb9637c4e8f2b3048be951dd1e2de376a70e04e02a2b497645a8a70d9cc0118eb8812578c06abf4e3da7777520f36d81f5fbabc0160d5c6f2dcc08b829

test:
  secret_key_base: 125b535136607c820664084044ba7b766efbdb87c7e82f4a5dc540301ff30c68f6f170912e40bbfcf254ee04b3b6bbfa2663e6ae59a529a51c362b577ce1978f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
